### ISSUE TITLE
Buying Property 

### ISSUE THREAD

**Issue by Pavah-21** [1209simran/Land-Registry-Application#9]
![image](https://user-images.githubusercontent.com/75636198/149474340-7a20a416-081b-4987-a38f-e12f82130b6f.png)

I try to buy the property listed after all the previous steps, but this message comes up in Metamask. Is the issue pertaining to gas fee or something else. Do guide me. Also, what is the ideal amount to be listed for the property

**Comment by 1209simran** [comment]
The total amount of the property should be equal to or less than the ether balance present in the respective account.
